name: flutter_museum
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  flutter_screenutil: ^5.6.1

  # Font, Icon
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.5

  # Firebase
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.4
  cloud_firestore: ^4.3.1

  # Architecture
  get: ^4.6.5

  # Helper
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  lint: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/